# Generated by Django 3.2.7 on 2021-10-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_visualiser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
